
// on login page
export const GET_LOGIN_REQUEST = 'GET/GET_LOGIN_REQUEST';
export const GET_LOGIN_SUCCESS = 'GET/GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAILURE = 'GET/GET_LOGIN_FAILURE';
export const GET_REGISTER_REQUEST = 'GET/GET_REGISTER_REQUEST';
export const GET_REGISTER_SUCCESS = 'GET/GET_REGISTER_SUCCESS';
export const GET_REGISTER_FAILURE = 'GET/GET_REGISTER_FAILURE';
export const GET_LOGIN_RESET = 'GET/GET_LOGIN_RESET';
// on navbar logout button
export const GET_LOGOUT = 'GET/GET_LOGOUT_SUCCESS';
